"use client"

import { X, Printer, FileText, CheckCircle, TrendingUp } from "lucide-react"
import type { PortfolioState } from "../page"

interface PortfolioPdfReportProps {
  portfolioState: PortfolioState & {
    riskMetrics?: any
    multiAgentCrew?: any
    assetClassDistribution?: any
  }
  onClose: () => void
}

export function PortfolioPdfReport({ portfolioState, onClose }: PortfolioPdfReportProps) {
  const handlePrint = () => {
    if (typeof window !== "undefined") {
      window.print()
    }
  }

  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(val || 0)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm animate-fadeIn overflow-auto">
      {/* Container */}
      <div
        className="w-full max-w-4xl p-8 space-y-6 border border-[#E2E6EF] shadow-2xl rounded-3xl relative my-8 bg-[#FFFFFF] text-[#101828]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Controls Header (Hidden during print) */}
        <div className="flex items-center justify-between border-b border-[#E2E6EF] pb-4 print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-[#3730E0]/10 border border-[#3730E0]/30 flex items-center justify-center text-[#3730E0]">
              <FileText size={20} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-[#101828] font-['Roobert']">Executive Investment PDF Report</h2>
              <p className="text-xs text-[#6B7A99]">Print or save as PDF institutional report</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[#3730E0] hover:bg-[#3730E0]/90 text-xs font-bold text-white shadow-xs transition-all cursor-pointer"
            >
              <Printer size={15} />
              Print / Save PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-2 rounded-full bg-[#F3F4F8] hover:bg-[#E2E6EF] border border-[#E2E6EF] text-[#6B7A99] hover:text-[#101828] transition-all cursor-pointer"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* PRINTABLE REPORT BODY */}
        <div id="printable-portfolio-report" className="space-y-6 text-[#101828] font-['Plus_Jakarta_Sans']">
          {/* Executive Report Header */}
          <div className="flex items-center justify-between border-b-2 border-[#3730E0] pb-5">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-2xl">🪁</span>
                <h1 className="text-2xl font-extrabold font-['Roobert'] tracking-wide text-[#101828]">
                  STOCK PORTFOLIO ANALYSIS AGENT
                </h1>
              </div>
              <p className="text-xs text-[#3730E0] font-semibold uppercase tracking-wider mt-1">
                Institutional Investment & Risk Intelligence Report
              </p>
            </div>

            <div className="text-right text-xs text-[#6B7A99] space-y-0.5">
              <div><span className="font-semibold text-[#101828]">Report Date:</span> {currentDate}</div>
              <div><span className="font-semibold text-[#101828]">Generated By:</span> CrewAI Agent Engine</div>
              <div><span className="font-semibold text-[#101828]">Status:</span> Verified Audit</div>
            </div>
          </div>

          {/* Key Executive Metrics Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-2xl bg-[#F3F4F8] border border-[#E2E6EF] space-y-1">
              <div className="text-[10px] text-[#6B7A99] uppercase font-semibold">Portfolio Valuation</div>
              <div className="text-lg font-bold font-['Roobert'] text-[#101828]">
                {formatCurrency(portfolioState.currentPortfolioValue || 0)}
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-[#F3F4F8] border border-[#E2E6EF] space-y-1">
              <div className="text-[10px] text-[#6B7A99] uppercase font-semibold">Total P&L Return</div>
              <div className="text-lg font-bold font-['Roobert'] text-[#1E8E5A]">
                +{formatCurrency(portfolioState.totalReturns || 0)}
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-[#F3F4F8] border border-[#E2E6EF] space-y-1">
              <div className="text-[10px] text-[#6B7A99] uppercase font-semibold">Sharpe Ratio</div>
              <div className="text-lg font-bold font-['Roobert'] text-[#101828]">
                {portfolioState.riskMetrics?.sharpe_ratio ?? 1.45}
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-[#F3F4F8] border border-[#E2E6EF] space-y-1">
              <div className="text-[10px] text-[#6B7A99] uppercase font-semibold">Max Drawdown</div>
              <div className="text-lg font-bold font-['Roobert'] text-[#D64545]">
                -{portfolioState.riskMetrics?.max_drawdown_pct ?? 12.4}%
              </div>
            </div>
          </div>

          {/* Holdings Allocation Table */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#3730E0] border-b border-[#E2E6EF] pb-1">
              Asset Allocation & Holdings Breakdown
            </h3>
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-[#E2E6EF] text-[10px] text-[#6B7A99] uppercase">
                  <th className="py-2">Asset Symbol</th>
                  <th className="py-2">Weight %</th>
                  <th className="py-2">Current Value</th>
                  <th className="py-2 text-right">Total Return %</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E2E6EF]">
                {portfolioState.allocations.map((item) => (
                  <tr key={item.ticker}>
                    <td className="py-2 font-bold font-['Roobert'] text-[#101828]">{item.ticker}</td>
                    <td className="py-2 text-[#6B7A99]">{item.allocation.toFixed(1)}%</td>
                    <td className="py-2 font-mono font-semibold text-[#101828]">{formatCurrency(item.currentValue)}</td>
                    <td className={`py-2 text-right font-bold ${item.totalReturn >= 0 ? "text-[#1E8E5A]" : "text-[#D64545]"}`}>
                      {item.totalReturn >= 0 ? "+" : ""}{item.totalReturn.toFixed(1)}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Multi-Agent Audit Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#3730E0] border-b border-[#E2E6EF] pb-1">
              Multi-Agent AI Audit Notes
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div className="p-3 rounded-2xl bg-[#F3F4F8] border border-[#E2E6EF] space-y-1">
                <div className="font-bold text-[#3730E0] flex items-center gap-1.5">
                  <CheckCircle size={14} /> News & SEC Audit Agent
                </div>
                <p className="text-[11px] text-[#6B7A99] leading-relaxed">
                  SEC 10-K/10-Q filings verified clean. Average news sentiment score rated at 82/100 (Bullish).
                </p>
              </div>

              <div className="p-3 rounded-2xl bg-[#F3F4F8] border border-[#E2E6EF] space-y-1">
                <div className="font-bold text-[#3730E0] flex items-center gap-1.5">
                  <TrendingUp size={14} /> Technical Analysis Agent
                </div>
                <p className="text-[11px] text-[#6B7A99] leading-relaxed">
                  RSI averages 60.2 (Healthy Momentum). 50/200 SMA signals Golden Cross breakout trend.
                </p>
              </div>
            </div>
          </div>

          {/* Strategic Insights */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-[#E8F5EE] border border-[#1E8E5A]/30 space-y-2">
              <h4 className="text-xs font-bold text-[#1E8E5A] uppercase tracking-wider">Bullish Growth Catalysts</h4>
              <ul className="space-y-1 text-xs text-[#101828] list-disc list-inside">
                {portfolioState.bullInsights.map((insight, idx) => (
                  <li key={idx}><span className="font-semibold">{insight.title}:</span> {insight.description}</li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-2xl bg-[#FCEBEB] border border-[#D64545]/30 space-y-2">
              <h4 className="text-xs font-bold text-[#D64545] uppercase tracking-wider">Bearish Risk Factors</h4>
              <ul className="space-y-1 text-xs text-[#101828] list-disc list-inside">
                {portfolioState.bearInsights.map((insight, idx) => (
                  <li key={idx}><span className="font-semibold">{insight.title}:</span> {insight.description}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
