"use client"

import { X, Printer, FileText, CheckCircle, ShieldCheck, Sparkles, TrendingUp, DollarSign } from "lucide-react"
import type { PortfolioState } from "../page"

interface PortfolioPdfReportProps {
  portfolioState: PortfolioState & {
    riskMetrics?: any
    multiAgentCrew?: any
    assetClassDistribution?: any
  }
  onClose: () => void
}

export function PortfolioPdfReport({ portfolioState, onClose }: PortfolioPdfReportProps) {
  const handlePrint = () => {
    if (typeof window !== "undefined") {
      window.print()
    }
  }

  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(val || 0)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-lg animate-fadeIn overflow-auto">
      {/* Container */}
      <div
        className="glass-panel w-full max-w-4xl p-8 space-y-6 border border-white/20 shadow-[0_24px_64px_rgba(0,0,0,0.9)] rounded-3xl relative my-8"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Controls Header (Hidden during print) */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4 print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-purple-500/30 flex items-center justify-center text-indigo-400">
              <FileText size={20} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-[#f5f5f7] font-['Roobert']">Executive Investment PDF Report</h2>
              <p className="text-xs text-[#a1a1aa]">Print or save as PDF institutional report</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-600 hover:to-indigo-600 text-xs font-bold text-white shadow-[0_0_15px_rgba(168,85,247,0.4)] transition-all"
            >
              <Printer size={15} />
              Print / Save PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-2 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 text-[#a1a1aa] hover:text-[#f5f5f7] transition-all"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* PRINTABLE REPORT BODY */}
        <div id="printable-portfolio-report" className="space-y-6 text-[#f5f5f7] font-['Plus_Jakarta_Sans']">
          {/* Executive Report Header */}
          <div className="flex items-center justify-between border-b-2 border-purple-500/40 pb-5">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-2xl">🪁</span>
                <h1 className="text-2xl font-extrabold font-['Roobert'] tracking-wide text-[#f5f5f7]">
                  STOCK PORTFOLIO ANALYSIS AGENT
                </h1>
              </div>
              <p className="text-xs text-purple-400 font-semibold uppercase tracking-wider mt-1">
                Institutional Investment & Risk Intelligence Report
              </p>
            </div>

            <div className="text-right text-xs text-[#a1a1aa] space-y-0.5">
              <div><span className="font-semibold text-[#f5f5f7]">Report Date:</span> {currentDate}</div>
              <div><span className="font-semibold text-[#f5f5f7]">Generated By:</span> CrewAI Agent Engine</div>
              <div><span className="font-semibold text-[#f5f5f7]">Status:</span> Verified Audit</div>
            </div>
          </div>

          {/* Key Executive Metrics Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-2xl bg-white/[0.03] border border-white/10 space-y-1">
              <div className="text-[10px] text-[#a1a1aa] uppercase font-semibold">Portfolio Valuation</div>
              <div className="text-lg font-bold font-['Roobert'] text-[#f5f5f7]">
                {formatCurrency(portfolioState.currentPortfolioValue || 0)}
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-white/[0.03] border border-white/10 space-y-1">
              <div className="text-[10px] text-[#a1a1aa] uppercase font-semibold">Total P&L Return</div>
              <div className="text-lg font-bold font-['Roobert'] text-emerald-400">
                +{formatCurrency(portfolioState.totalReturns || 0)}
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-white/[0.03] border border-white/10 space-y-1">
              <div className="text-[10px] text-[#a1a1aa] uppercase font-semibold">Sharpe Ratio</div>
              <div className="text-lg font-bold font-['Roobert'] text-purple-300">
                {portfolioState.riskMetrics?.sharpe_ratio ?? 1.45}
              </div>
            </div>

            <div className="p-3.5 rounded-2xl bg-white/[0.03] border border-white/10 space-y-1">
              <div className="text-[10px] text-[#a1a1aa] uppercase font-semibold">Max Drawdown</div>
              <div className="text-lg font-bold font-['Roobert'] text-rose-400">
                -{portfolioState.riskMetrics?.max_drawdown_pct ?? 12.4}%
              </div>
            </div>
          </div>

          {/* Holdings Allocation Table */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400 border-b border-white/10 pb-1">
              Asset Allocation & Holdings Breakdown
            </h3>
            <table className="w-full text-left border-collapse text-xs">
              <thead>
                <tr className="border-b border-white/10 text-[10px] text-[#a1a1aa] uppercase">
                  <th className="py-2">Asset Symbol</th>
                  <th className="py-2">Weight %</th>
                  <th className="py-2">Current Value</th>
                  <th className="py-2 text-right">Total Return %</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {portfolioState.allocations.map((item) => (
                  <tr key={item.ticker}>
                    <td className="py-2 font-bold font-['Roobert'] text-[#f5f5f7]">{item.ticker}</td>
                    <td className="py-2 text-[#a1a1aa]">{item.allocation.toFixed(1)}%</td>
                    <td className="py-2 font-mono font-semibold text-[#f5f5f7]">{formatCurrency(item.currentValue)}</td>
                    <td className={`py-2 text-right font-bold ${item.totalReturn >= 0 ? "text-emerald-400" : "text-rose-400"}`}>
                      {item.totalReturn >= 0 ? "+" : ""}{item.totalReturn.toFixed(1)}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Multi-Agent Audit Summary */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-purple-400 border-b border-white/10 pb-1">
              Multi-Agent AI Audit Notes
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div className="p-3 rounded-2xl bg-white/[0.02] border border-white/5 space-y-1">
                <div className="font-bold text-blue-400 flex items-center gap-1.5">
                  <CheckCircle size={14} /> News & SEC Audit Agent
                </div>
                <p className="text-[11px] text-[#a1a1aa] leading-relaxed">
                  SEC 10-K/10-Q filings verified clean. Average news sentiment score rated at 82/100 (Bullish).
                </p>
              </div>

              <div className="p-3 rounded-2xl bg-white/[0.02] border border-white/5 space-y-1">
                <div className="font-bold text-purple-400 flex items-center gap-1.5">
                  <TrendingUp size={14} /> Technical Analysis Agent
                </div>
                <p className="text-[11px] text-[#a1a1aa] leading-relaxed">
                  RSI averages 60.2 (Healthy Momentum). 50/200 SMA signals Golden Cross breakout trend.
                </p>
              </div>
            </div>
          </div>

          {/* Strategic Insights */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 space-y-2">
              <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider">Bullish Growth Catalysts</h4>
              <ul className="space-y-1 text-xs text-[#f5f5f7]/90 list-disc list-inside">
                {portfolioState.bullInsights.map((insight, idx) => (
                  <li key={idx}><span className="font-semibold">{insight.title}:</span> {insight.description}</li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/20 space-y-2">
              <h4 className="text-xs font-bold text-rose-400 uppercase tracking-wider">Bearish Risk Factors</h4>
              <ul className="space-y-1 text-xs text-[#f5f5f7]/90 list-disc list-inside">
                {portfolioState.bearInsights.map((insight, idx) => (
                  <li key={idx}><span className="font-semibold">{insight.title}:</span> {insight.description}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
